### ISSUE TITLE
alpine容器镜像中生成火焰图错误的其它解决方案

### ISSUE THREAD

**Issue by shalousun** [alibaba/arthas#1602]
# 错误描述
````
[arthas@1]$ profiler start
Perf events unavailable. See stderr of the target process.
````
>在alpine镜像中执行`profiler start`命令后可能还会发现alpine基础镜像中缺乏libstdc++.so.6库，这时在自己的基础镜像中添加下libstdc++下就好了。

这个问题通常是出现在容器环境中。
arthas实际是利用`async-profiler`去完成的。在[async-profiler](https://github.com/jvm-profiling-tools/async-profiler)官方地址的README中有提到该问题。

# async-profiler官方对问题描述和解决方法

```
Perf events unavailble. See stderr of the target process.
```

perf_event_open() syscall has failed. The error message is printed to the error stream of the target JVM.

Typical reasons include:

- /proc/sys/kernel/perf_event_paranoid is set to restricted mode (>=2).
/proc/sys/kernel/perf_event_paranoid 设置为受限模式（> = 2）
- seccomp disables perf_event_open API in a container(seccomp禁用容器中的perf_event_open API。).

- OS runs under a hypervisor that does not virtualize performance counters.(操作系统在不虚拟化性能计数器的管理程序下运行。)
- perf_event_open API is not supported on this system, e.g. WSL.(该系统不支持perf_event_open API，例如WSL。)

根据async-profiler官方的说明来看下系统的`/proc/sys/kernel/perf_event_paranoid `这个配置项。

```
bash-4.4# cat /proc/sys/kernel/perf_event_paranoid
2
```
发现该系统配置参数的值确实是大于等于2。
根据官方文档的描述。尝试将`/proc/sys/kernel/perf_event_paranoid`的值设置为1。

```
bash-4.4# echo 1 > /proc/sys/kernel/perf_event_paranoid
bash-4.4# bash: /proc/sys/kernel/perf_event_paranoid: Read-only file system
```
说明权限不足。通常情况下基础镜像的都是使用的非root权限。如果我们硬要修改这个配置项，第一想到的可能只能重新构建镜像了。在构建镜像的时候修改基础镜像的用户，然后设置系统参数。

带来新的问题：

- 新的基础镜像变更后带来了安全问题。
- 所有需要的尝试生成火焰图的应用都更改基础镜像。

# 解决方法
稍微思考下，我们发现在kubernetes或者docker中是允许我们变更容器的权限。

在docker中可以使用`--cap-add SYS_ADMIN`命令选项来指定。

```
docker run  --cap-add=SYS_ADMIN {container}
```
在kubernetes中可以通过`securityContext`来设置。修改你的deployment部署文件，配置参考如下。

```
containers:
    - name: springboot-tomcat
      image: registry.cn-shanghai.aliyuncs.com/shalousun/springboot:2.3.4-tomcat
      imagePullPolicy: Always
      securityContext:
        capabilities:
          add: ["SYS_ADMIN"]

```
配置好后重新在kubernetes中部署就好了。部署好重新进入容器后就可以正常按照arthas官方的命令执行了。

```
[arthas@1]$ profiler start
Started [cpu] profiling
[arthas@1]$ profiler getSamples
3
[arthas@1]$ profiler status
[perf] profiling is running for 28 seconds
[arthas@1]$ profiler stop
OK
profiler output file: /arthas-output/20201109-181906.svg
```
